config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'home/mission'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def mission
  end
end

app/controllers/issue_controller.rb
class IssueController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= image_tag("mountside.png", class: "fixed bottom-0 right-0 -z-10") %>

<div class="poem">
  <p class="font-aboreto text-2xl my-6">The Better Part of Yesterday</p>
  <p>My heart is a deserted street<br>in the middle of winter, dead<br>leaves skittering in the dying<br>afternoon light. I am a stop sign<br>riddled with bullet holes,<br>pinpricks of sunlight streaming<br>through me. And you? You are<br>everything –the light and shadow,<br>the broken glass pane in which you<br>can see everything. You are a street<br>upon which I used to live, and I<br>don’t need a house to haunt you.
</p>
  <p class="font-bold self-start mr-20 ml-[15%] transition-all">- M. Brooks</p>
</div>
<div class="poem">
  <p class="font-aboreto text-2xl my-6">Big Cut Station, Virginia</p>
  <p>I came late into the world, to<br>my folks and their kin before<br>them. I didn’t come by the behest<br>of some country to be beholden.<br>And the love of Mama and Pa<br>was the Gum Arabic<br>to the blackberry ink of their<br>mixed blood in me.<br>Where my cheeks are pocked<br>with iodine stains, I have shorn<br>my wilderness, have nicked<br>my past uneasily:<br>my highland way, torn between<br>allegiance to a dignity<br>I don’t need to flaunt, and a<br>preference for warmth<br>in the windborne<br>cliffs that never howl my name. 
</p>
  <p class="font-bold self-start mr-20 ml-[15%] transition-all">- W. R. Moore</p>
</div>
<div class="poem">
  <p class="font-aboreto text-2xl my-6">Flowered</p>
  <p>Skin so red, it’s not the blood, but petals fallen from the poppies<br>growing on his grave.<br>He fell, you broke under his gaze, and shells you gathered on the beach were rubble,<br>broken feet from stepping over, finding no one.<br>Shards were words he gasped in tongues you couldn’t recognise,<br>now you can’t ask him as he chose the easy way,<br>a tattered note, letters you were blinded to and couldn’t bear to read<br>until the anger cooled.<br>Now you’re left with bitterness, and everything tastes sour<br>except the sweet taste of finality.
  </p>
  <p class="font-bold self-start mr-20 ml-[15%] transition-all">- E. Rosier</p>
</div>



<div class="flex flex-col ml-6 mt-6 font-aboreto h-[40vh]">
  <%= link_to "Mission", home_mission_path, class: ""%>
  <%# link_to "Issue Zero", issue_zero_path, class: ""%>
  <% @asset = asset_url("issuezero.pdf") %>
  <%= link_to "Issue Zero", pdfjs.minimal_path(file: @asset) %>
</div>

app/views/home/mission.html.erb
<%= image_tag("mountside.png", class: "fixed bottom-0 right-0") %>

<div class="mt-12 flex flex-col w-full items-center">
  <p class="font-aboreto md:text-4xl text-2xl transition-all">Mission</p>
  <p class="font-cormorant md:text-xl text-lg mt-4 transition-all">Print the good stuff</p>
</div>

app/views/layouts/_alert.html.erb
<div class="container-alert" data-controller="alert"> 
  <div class="alert bg-orange-300">
    <%= notice %>
    <button class="font-cormorant text-3xl" data-action="alert#close" aria-label="Close">x</button>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav data-controller="navbar" class="sticky top-0 bg-green-900 no-underline w-full px-4 md:px-12 py-2">
  <div class="flex flex-row items-center justify-between">
    <div class="font-aboreto transition-all text-2xl md:text-4xl lg:text-6xl text-white"><span class="text-xl lg:text-2xl font-josefin align-middle">the</span>L<span class="text-2xl lg:text-3xl align-top font-josefin -ml-1 md:-ml-2">one</span>M<span class="text-2xl align-top lg:text-3xl font-josefin md:-ml-1">ountain</span>L<span class="text-2xl align-middle lg:text-3xl font-josefin md:-ml-1">iterary</span>S<span class="text-2xl lg:text-3xl align-bottom font-josefin">ociety</span></div>
    <div class="flex flex-col items-center gap-2 font-josefin text-white">
      <div class="font-aboreto text-md md:text-lg lg:text-xl transition-all">Support</div>
      <div class="flex flex-row justify-evenly gap-2 text-md lg:text-lg transition-all">
        <p class="">Subscribe</p>
        <span>~</span>
        <p class="">Donate</p>
      </div>
    </div>
  </div>
  <div class="flex flex-row justify-center px-12 font-aboreto font-bold text-md lg:text-lg text-white gap-4 md:gap-6 lg:gap-8 transition-all ml-2">
    <p>Fiction</p>
    <p>Poetry</p>
    <p>Art</p>
    <p>Interviews</p>
    <p>Folios</p>
    <p>Profiles</p>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="container-alert" data-controller="alert"> 
  <div class="notice" role="notice">
    <%= notice %>
    <button class="font-cormorant text-3xl" data-action="alert#close" aria-label="Close">x</button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lone Mountain Society</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Cormorant+Garamond:wght@400;700&family=Josefin+Slab&display=swap" rel="stylesheet">
  </head>

   <% if notice %>
    <div class="flex flex-row absolute left-10 bottom-10">
      <%= render 'layouts/notice' %>
    </div>
  <% end %>
  
  <% if alert %>
    <div class="flex flex-row absolute left-10 bottom-10">
      <%= render 'layouts/alert' %>
    </div>
  <% end %>

  <body class="bg-fixed bg-oversize bg-gradient-to-bl from-yellow-100 via-amber-200 to-orange-300">
    <main class="flex flex-col w-[100vw]">
      <%= render 'layouts/nav' %>
      <%= yield %>
    </main>
  </body>
</html>